title: "Farhad Uneci"

tagline: "Software engineering student"

description: "A Software engineering student trying to be eager about anything related to computers."

author: "Farhad Uneci"

twitter:
  username: farhaduneci
  card: summary

url: "https://farhaduneci.github.io/unecicodes"

defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

social:
  name: Farhad Uneci
  links:
    - https://github.com/farhaduneci    
    - https://twitter.com/farhaduneci
    - https://instagram.com/unecicodes
    - https://www.linkedin.com/in/farhaduneci

exclude: 
  - index.js
  - index.html
  - css/style.css
  - README.md